FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/data_source/finnhub_client.py ./src/finnhub_client.py
COPY config/ ./config/
RUN mkdir -p /app/logs && chown -R 1000:1000 /app/logs
USER 1000
CMD ["python", "src/finnhub_client.py"]