apiVersion: apps/v1
kind: Deployment
metadata:
  name: finnhub-client
  labels:
    app: finnhub-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finnhub-client
  template:
    metadata:
      labels:
        app: finnhub-client
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: finnhub-client
        image: finnhub-client:1.0
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
