apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.0
          ports:
            - containerPort: 7077
              name: spark
            - containerPort: 8080
              name: webui
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_MASTER_HOST
              value: "spark-master"
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
